name: Doxygen Documentation

on:
  push:
    tags:
      - "*"
    branches: [feature/8-cmake-dependency-graph-doxygen]

jobs:
  build:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install
        run: |
          sudo apt-get install doxygen
          pip install jinja2 Pygments
      - name: Prepare
        run: |
          rm -rf docs/html
          rm -rf build
          mkdir build
      - name: Configure
        run: |
          cmake -H. -Bbuild -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Release"
      - name: Building
        run: |
          cmake --build build --config Release --target doxygen_docs -j4
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build_dir: ./docs/html
