# Generate Doxygen documentation using CMake targe and publish it to GitHub Pages
name: Doxygen Documentation

on:
  # push:
  #   branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install
        run: |
          sudo apt-get install doxygen graphviz
          pip install jinja2 Pygments
      - name: Configure
        run: |
          cmake -H. -Bbuild -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Release"
      - name: Build
        run: |
          cmake --build build --config Release --target doxygen_docs -j4
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build_dir: ./docs/html
