name: Hello World on Windows

on:
  push:
    branches: ["feature/6-cmake-based-multi-platform-projects"]

jobs:
  say-hello:
    runs-on: windows-latest
    steps:
      - name: Say Hello
        run: echo "Hello, world!"
